import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  scroll: { flex: 1 },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerSub: { fontSize: 10, color: colors.textFaint, letterSpacing: 1, textTransform: "uppercase" },
  headerTitle: { fontSize: 24, fontWeight: "bold", color: "#fff" },

  // Filtros
  filtrosScroll: { marginBottom: 16 },
  filtrosContent: { paddingHorizontal: 16, gap: 8 },
  filtroPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  filtroPillAtivo: {
    backgroundColor: "#E13A3E", // Cor de destaque dos filtros na imagem
    borderColor: "#E13A3E",
  },
  filtroTexto: { fontSize: 12, color: colors.textMuted, fontWeight: "600" },
  filtroTextoAtivo: { color: "#fff" },

  // Resumo Grid
  resumoGrid: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 24,
  },
  resumoCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    height: 60,
  },
  resumoValor: { fontSize: 16, fontWeight: "bold", color: "#fff" }, // Cores variam na imagem (rosa, amarelo, azul)
  resumoLabel: { fontSize: 9, color: colors.textFaint, marginTop: 2 },

  // Seções de Países
  section: { paddingHorizontal: 16, marginBottom: 20 },
  sectionTitle: {
    fontSize: 11,
    color: colors.textFaint,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 12,
    textTransform: "uppercase",
  },

  // Card de Estádio
  estadioCard: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  estadioCardIconico: {
    backgroundColor: "rgba(239, 159, 39, 0.05)",
    borderColor: "rgba(239, 159, 39, 0.3)",
  },
  estadioCardFinal: {
    backgroundColor: "rgba(139, 61, 68, 0.05)",
    borderColor: "rgba(139, 61, 68, 0.3)",
  },
  estadioRow: { flexDirection: "row", gap: 12, marginBottom: 12 },
  estadioIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  estadioInfo: { flex: 1 },
  estadioHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  estadioNome: { fontSize: 16, fontWeight: "bold", color: "#fff" },
  estadioBadgeIconico: {
    backgroundColor: "rgba(239, 159, 39, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 6,
  },
  estadioBadgeTextoIconico: { fontSize: 9, color: colors.goldLight, fontWeight: "bold" },
  estadioLocal: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  estadioXp: { fontSize: 11, fontWeight: "bold", color: colors.goldLight },

  // Barra de Progresso
  progressContainer: { marginTop: 4 },
  progressBg: { height: 4, backgroundColor: "rgba(255,255,255,0.1)", borderRadius: 2, flex: 1 },
  progressFill: { height: 4, borderRadius: 2 },
  progressRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
  progressPct: { fontSize: 10, color: colors.textFaint, fontWeight: "600", minWidth: 30, textAlign: "right" },

  // --- DETALHES ---
  detailHeader: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 30 },
  detailTitle: { fontSize: 32, fontWeight: "bold", color: "#fff", marginTop: 20 },
  detailLocalRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 4 },
  detailPais: { fontSize: 12, fontWeight: "bold", color: colors.textMuted },
  detailCidade: { fontSize: 12, color: colors.textMuted },

  rewardBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 20,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  rewardLabel: { fontSize: 11, color: colors.textFaint, marginBottom: 4 },
  rewardText: { fontSize: 16, fontWeight: "bold", color: colors.goldLight },
  rewardIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },

  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 30,
  },
  infoCard: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  infoLabel: { fontSize: 9, color: colors.textFaint, textTransform: "uppercase", marginBottom: 8, letterSpacing: 0.5 },
  infoValor: { fontSize: 20, fontWeight: "bold", color: "#fff" },
  infoSub: { fontSize: 11, color: colors.textMuted, marginTop: 4 },

  sobreSection: { paddingHorizontal: 20, marginBottom: 30 },
  sobreTitulo: { fontSize: 12, color: colors.gold, fontWeight: "bold", letterSpacing: 1, textTransform: "uppercase", marginBottom: 16 },
  sobreTexto: { fontSize: 14, color: colors.textPrimary, lineHeight: 22 },

  historicoSection: { paddingHorizontal: 20, marginBottom: 30 },
  historicoItem: { flexDirection: "row", gap: 16, marginBottom: 24 },
  historicoIconCol: { alignItems: "center" },
  historicoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  historicoLinha: {
    position: "absolute",
    top: 40,
    bottom: -24,
    width: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  historicoContent: { flex: 1, paddingTop: 4 },
  historicoTitulo: { fontSize: 15, fontWeight: "bold", color: "#fff", marginBottom: 4 },
  historicoAno: { fontSize: 12, color: colors.textMuted, marginBottom: 4 },
  historicoDesc: { fontSize: 13, color: colors.textFaint, lineHeight: 18 },
  badgeEmBreve: {
    backgroundColor: "rgba(225, 58, 62, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 6,
  },
  badgeEmBreveTexto: { fontSize: 9, color: "#E13A3E", fontWeight: "bold" },

  figurinhaSection: { paddingHorizontal: 20, marginBottom: 40 },
  figurinhaCard: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  figurinhaIcon: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  figurinhaInfo: { flex: 1 },
  figurinhaNome: { fontSize: 15, fontWeight: "bold", color: "#fff" },
  figurinhaSub: { fontSize: 11, color: colors.textFaint, marginTop: 2 },
  figurinhaStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(45, 106, 79, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  figurinhaStatusTexto: { fontSize: 11, fontWeight: "bold", color: "#52B788" },

  // --- MODAL (Baseado em albumStyles.ts) ---
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  modalClose: {
    position: "absolute",
    right: 16,
    top: 16,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalImageContainer: {
    width: 200,
    height: 200,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  modalImage: { width: "100%", height: "100%" },
  modalName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 4,
    textAlign: "center",
  },
  modalSelection: {
    fontSize: 16,
    color: colors.goldLight,
    fontWeight: "600",
    marginBottom: 16,
  },
  modalInfoRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  modalInfoBadge: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: "center",
  },
  modalInfoLabel: {
    fontSize: 10,
    color: colors.textMuted,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  modalInfoValue: {
    fontSize: 12,
    color: "#FFF",
    fontWeight: "bold",
  },
  modalRarityBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    backgroundColor: "#26215C", // Padrão Estádios (Raro/Lendário)
  },
  modalRarityText: {
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 1,
    color: "#CECBF6",
  },
});
