import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  scroll: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerSub: {
    fontSize: 10,
    color: colors.textFaint,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  headerTitle: { fontSize: 24, fontWeight: "bold", color: "#fff" },
  filtrosScroll: { marginBottom: 16 },
  filtrosContent: { paddingHorizontal: 16, gap: 8 },
  filtroPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  filtroPillAtivo: {
    backgroundColor: colors.gold,
    borderColor: colors.gold,
  },
  filtroTexto: { fontSize: 12, color: colors.textMuted, fontWeight: "600" },
  filtroTextoAtivo: { color: colors.bg, fontWeight: "700" },
  resumoGrid: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 24,
  },
  resumoCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    height: 60,
  },
  resumoValor: { fontSize: 16, fontWeight: "bold", color: "#fff" },
  resumoLabel: { fontSize: 9, color: colors.textFaint, marginTop: 2 },
  destaqueSection: { paddingHorizontal: 16, marginBottom: 24 },
  sectionTitle: {
    fontSize: 11,
    color: colors.textFaint,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  destaqueCard: {
    backgroundColor: "rgba(239,159,39,0.08)",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(239,159,39,0.35)",
    gap: 10,
  },
  destaqueTop: { flexDirection: "row", alignItems: "center", gap: 10 },
  destaqueIcone: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  destaqueTopTextos: { flex: 1 },
  destaqueAno: { fontSize: 20, color: "#fff", fontWeight: "bold" },
  destaqueLocal: { fontSize: 12, color: colors.textMuted, marginTop: 1 },
  destaqueBadge: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  destaqueBadgeText: { color: colors.goldLight, fontSize: 10, fontWeight: "700" },
  destaqueLinha: { height: 1, backgroundColor: "rgba(255,255,255,0.12)" },
  destaqueTitulo: { fontSize: 16, color: "#fff", fontWeight: "700" },
  destaqueSub: { fontSize: 12, color: colors.textMuted },
  destaqueBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  destaqueFinal: { fontSize: 11, color: colors.textFaint },
  destaqueXp: {
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  destaqueXpText: { fontSize: 10, color: colors.goldLight, fontWeight: "700" },
  listaSection: { paddingHorizontal: 16, marginBottom: 24 },
  copaItem: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  copaItemIcone: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  copaItemInfo: { flex: 1 },
  copaItemAno: { fontSize: 16, color: "#fff", fontWeight: "700" },
  copaItemSub: { fontSize: 12, color: colors.textMuted, marginTop: 1 },
  copaItemLinha: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 6 },
  copaItemLinhaTexto: { fontSize: 11, color: colors.textFaint },
  copaItemMeta: { alignItems: "flex-end", gap: 6 },
  copaItemMetaBadge: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  copaItemMetaBadgeText: { fontSize: 10, color: colors.textMuted, fontWeight: "600" },
  copaItemMetaXp: { fontSize: 10, color: colors.goldLight, fontWeight: "700" },
  detailHero: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 34,
    position: "relative",
    overflow: "hidden",
  },
  detailHeroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  detailBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  detailAno: { fontSize: 52, color: "rgba(255,255,255,0.2)", fontWeight: "900", textAlign: "center" },
  detailSub: {
    fontSize: 10,
    color: "rgba(255,255,255,0.55)",
    letterSpacing: 2,
    textTransform: "uppercase",
    textAlign: "center",
    marginTop: 4,
  },
  detailTitle: { fontSize: 30, color: "#fff", fontWeight: "bold", textAlign: "center", marginTop: 2 },
  detailLocalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 6,
  },
  detailLocalText: { fontSize: 13, color: "rgba(255,255,255,0.75)" },
  detailFaseBadge: {
    backgroundColor: "rgba(255,255,255,0.16)",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 8,
  },
  detailFaseText: { fontSize: 11, color: "#fff", fontWeight: "700" },
  rewardBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  rewardLabel: { fontSize: 11, color: colors.textFaint, marginBottom: 4 },
  rewardText: { fontSize: 16, fontWeight: "bold", color: colors.goldLight },
  rewardIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 30,
  },
  infoCard: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  infoLabel: { fontSize: 9, color: colors.textFaint, textTransform: "uppercase", marginBottom: 8, letterSpacing: 0.5 },
  infoValor: { fontSize: 18, color: "#fff", fontWeight: "700" },
  infoSub: { fontSize: 11, color: colors.textMuted, marginTop: 3 },
  sobreSection: { paddingHorizontal: 20, marginBottom: 30 },
  sobreTitulo: {
    fontSize: 12,
    color: colors.gold,
    fontWeight: "bold",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  sobreTexto: { fontSize: 14, color: colors.textPrimary, lineHeight: 22 },
  curiosidadesSection: { paddingHorizontal: 20, marginBottom: 30 },
  curiosidadeItem: { flexDirection: "row", gap: 10, marginBottom: 12, alignItems: "flex-start" },
  curiosidadeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.gold,
    marginTop: 6,
  },
  curiosidadeTexto: { fontSize: 14, color: colors.textPrimary, lineHeight: 20, flex: 1 },
  historicoSection: { paddingHorizontal: 20, marginBottom: 30 },
  historicoItem: { flexDirection: "row", gap: 16, marginBottom: 24 },
  historicoIconCol: { alignItems: "center" },
  historicoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  historicoLinha: {
    position: "absolute",
    top: 40,
    bottom: -24,
    width: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  historicoContent: { flex: 1, paddingTop: 4 },
  historicoTitulo: { fontSize: 15, fontWeight: "bold", color: "#fff", marginBottom: 4 },
  historicoAno: { fontSize: 12, color: colors.textMuted, marginBottom: 4 },
  historicoDesc: { fontSize: 13, color: colors.textFaint, lineHeight: 18 },
  badgeEmBreve: {
    backgroundColor: "rgba(225, 58, 62, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 6,
  },
  badgeEmBreveTexto: { fontSize: 9, color: "#E13A3E", fontWeight: "bold" },
  figurinhaSection: { paddingHorizontal: 20, marginBottom: 40 },
  figurinhaCard: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  figurinhaIcon: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: "rgba(239,159,39,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(239,159,39,0.3)",
  },
  figurinhaIconTexto: { fontSize: 16, color: colors.goldLight, fontWeight: "800" },
  figurinhaInfo: { flex: 1 },
  figurinhaNome: { fontSize: 15, fontWeight: "bold", color: "#fff" },
  figurinhaSub: { fontSize: 11, color: colors.textFaint, marginTop: 2 },
  figurinhaStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(45, 106, 79, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  figurinhaStatusTexto: { fontSize: 11, fontWeight: "bold", color: "#52B788" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: colors.bgCard,
  },
  modalClose: {
    position: "absolute",
    right: 16,
    top: 16,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalAnoContainer: {
    width: 120,
    height: 120,
    borderRadius: 24,
    backgroundColor: "rgba(239,159,39,0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(239,159,39,0.35)",
  },
  modalAno: { fontSize: 34, color: "#fff", fontWeight: "800" },
  modalName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 4,
    textAlign: "center",
  },
  modalSelection: {
    fontSize: 14,
    color: colors.goldLight,
    fontWeight: "600",
    marginBottom: 16,
  },
  modalInfoRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 24,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  modalInfoBadge: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: "center",
  },
  modalInfoLabel: {
    fontSize: 10,
    color: colors.textMuted,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  modalInfoValue: { fontSize: 12, color: "#FFF", fontWeight: "bold" },
  modalRarityBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    backgroundColor: colors.goldDark,
  },
  modalRarityText: {
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 1,
    color: colors.goldLight,
  },
});
