import { StyleSheet } from "react-native";
import { colors } from "./colors";

const purple = colors.purple;
const purpleLight = colors.purpleLight;
const purpleDark = colors.purpleDark;

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  scroll: { flex: 1 },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerSub: {
    fontSize: 10,
    color: colors.textFaint,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  headerTitle: { fontSize: 24, fontWeight: "bold", color: "#fff" },

  // Filtros
  filtrosScroll: { marginBottom: 16 },
  filtrosContent: { paddingHorizontal: 16, gap: 8 },
  filtroPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  filtroPillAtivo: {
    backgroundColor: purple,
    borderColor: purple,
  },
  filtroTexto: { fontSize: 12, color: colors.textMuted, fontWeight: "600" },
  filtroTextoAtivo: { color: "#fff" },

  // Resumo Grid
  resumoGrid: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 24,
  },
  resumoCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    height: 60,
  },
  resumoValor: { fontSize: 16, fontWeight: "bold", color: "#fff" },
  resumoLabel: { fontSize: 9, color: colors.textFaint, marginTop: 2 },

  // Seção atual
  atualSection: { paddingHorizontal: 16, marginBottom: 24 },
  sectionTitle: {
    fontSize: 11,
    color: colors.textFaint,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 12,
    textTransform: "uppercase",
  },

  // Card mascote atual (destaque)
  atualCard: {
    backgroundColor: "rgba(83, 74, 183, 0.1)",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(83, 74, 183, 0.4)",
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  atualEmoji: {
    width: 72,
    height: 72,
    borderRadius: 16,
    backgroundColor: "rgba(83, 74, 183, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  atualEmojiText: { fontSize: 36 },
  atualEmojiImage: {
    width: 62,
    height: 62,
    borderRadius: 12,
  },
  atualInfo: { flex: 1 },
  atualNome: { fontSize: 22, fontWeight: "bold", color: "#fff" },
  atualAnoBadge: {
    backgroundColor: purple,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginTop: 4,
    marginBottom: 6,
  },
  atualAnoBadgeText: { fontSize: 10, color: "#fff", fontWeight: "bold" },
  atualSub: { fontSize: 12, color: colors.textMuted, marginBottom: 8 },
  atualBottomRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  coletadaBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(45, 106, 79, 0.2)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  coletadaText: { fontSize: 11, color: colors.greenLight, fontWeight: "bold" },
  xpBadge: {
    backgroundColor: "rgba(239, 159, 39, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  xpText: { fontSize: 11, color: colors.goldLight, fontWeight: "bold" },

  // Grid de mascotes anteriores
  anterioresSection: { paddingHorizontal: 16, marginBottom: 24 },
  mascotesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  mascoteCard: {
    width: "47%",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  mascoteCardBloqueado: {
    opacity: 0.5,
  },
  mascoteCardColetado: {
    borderColor: "rgba(83, 74, 183, 0.3)",
    backgroundColor: "rgba(83, 74, 183, 0.05)",
  },
  mascoteCardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  mascoteEmojiContainer: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  mascoteEmoji: { fontSize: 28 },
  mascoteEmojiImage: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  mascoteXpBadge: {
    backgroundColor: "rgba(239, 159, 39, 0.15)",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
  },
  mascoteXpText: { fontSize: 9, color: colors.goldLight, fontWeight: "bold" },
  mascoteNome: { fontSize: 15, fontWeight: "bold", color: "#fff", marginBottom: 2 },
  mascoteSub: { fontSize: 11, color: colors.textMuted, marginBottom: 8 },
  mascoteBottomRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  mascoteColetadaBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(45, 106, 79, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  mascoteColetadaText: { fontSize: 10, color: colors.greenLight, fontWeight: "600" },
  mascoteBloqueadoBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  mascoteBloqueadoText: { fontSize: 10, color: colors.textFaint, fontWeight: "600" },

  // ─── DETALHES ───────────────────────────────────────────────────────────────

  detailHero: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 36,
    position: "relative",
    overflow: "hidden",
  },
  detailHeroOverlay: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  detailBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  detailEmojiGrande: {
    fontSize: 80,
    textAlign: "center",
    marginBottom: 12,
  },
  detailEmojiGrandeImage: {
    width: 160,
    height: 160,
    alignSelf: "center",
    marginBottom: 12,
    borderRadius: 16,
  },
  detailSub: {
    fontSize: 10,
    color: "rgba(255,255,255,0.5)",
    letterSpacing: 2,
    textAlign: "center",
    marginBottom: 4,
  },
  detailTitle: { fontSize: 32, fontWeight: "bold", color: "#fff", textAlign: "center" },
  detailLocalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 6,
  },
  detailPais: { fontSize: 13, color: "rgba(255,255,255,0.7)" },
  detailAnoBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: purple,
  },
  detailAnoBadgeText: { fontSize: 11, color: "#fff", fontWeight: "bold" },

  rewardBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 20,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  rewardLabel: { fontSize: 11, color: colors.textFaint, marginBottom: 4 },
  rewardText: { fontSize: 16, fontWeight: "bold", color: colors.goldLight },
  rewardIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },

  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 30,
  },
  infoCard: {
    width: "47%",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  infoLabel: {
    fontSize: 9,
    color: colors.textFaint,
    textTransform: "uppercase",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  infoValor: { fontSize: 20, fontWeight: "bold", color: "#fff" },
  infoSub: { fontSize: 11, color: colors.textMuted, marginTop: 4 },

  sobreSection: { paddingHorizontal: 20, marginBottom: 30 },
  sobreTitulo: {
    fontSize: 12,
    color: purpleLight,
    fontWeight: "bold",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  sobreTexto: { fontSize: 14, color: colors.textPrimary, lineHeight: 22 },

  curiosidadesSection: { paddingHorizontal: 20, marginBottom: 30 },
  curiosidadeItem: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
    alignItems: "flex-start",
  },
  curiosidadeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: purple,
    marginTop: 6,
  },
  curiosidadeTexto: { fontSize: 14, color: colors.textPrimary, lineHeight: 20, flex: 1 },

  historicoSection: { paddingHorizontal: 20, marginBottom: 30 },
  historicoItem: { flexDirection: "row", gap: 16, marginBottom: 24 },
  historicoIconCol: { alignItems: "center" },
  historicoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  historicoLinha: {
    position: "absolute",
    top: 40,
    bottom: -24,
    width: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  historicoContent: { flex: 1, paddingTop: 4 },
  historicoTitulo: { fontSize: 15, fontWeight: "bold", color: "#fff", marginBottom: 4 },
  historicoAno: { fontSize: 12, color: colors.textMuted, marginBottom: 4 },
  historicoDesc: { fontSize: 13, color: colors.textFaint, lineHeight: 18 },
  badgeEmBreve: {
    backgroundColor: "rgba(225, 58, 62, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 6,
  },
  badgeEmBreveTexto: { fontSize: 9, color: "#E13A3E", fontWeight: "bold" },

  figurinhaSection: { paddingHorizontal: 20, marginBottom: 40 },
  figurinhaCard: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  figurinhaIcon: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: "rgba(83,74,183,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  figurinhaIconText: { fontSize: 28 },
  figurinhaEmojiImage: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  figurinhaInfo: { flex: 1 },
  figurinhaNome: { fontSize: 15, fontWeight: "bold", color: "#fff" },
  figurinhaSub: { fontSize: 11, color: colors.textFaint, marginTop: 2 },
  figurinhaStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(45, 106, 79, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  figurinhaStatusTexto: { fontSize: 11, fontWeight: "bold", color: "#52B788" },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: purpleDark,
  },
  modalClose: {
    position: "absolute",
    right: 16,
    top: 16,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalEmojiContainer: {
    width: 120,
    height: 120,
    borderRadius: 24,
    backgroundColor: "rgba(83,74,183,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(83,74,183,0.3)",
  },
  modalEmoji: { fontSize: 64 },
  modalEmojiImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
  },
  modalName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 4,
    textAlign: "center",
  },
  modalSelection: {
    fontSize: 14,
    color: purpleLight,
    fontWeight: "600",
    marginBottom: 16,
  },
  modalInfoRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 24,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  modalInfoBadge: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: "center",
  },
  modalInfoLabel: {
    fontSize: 10,
    color: colors.textMuted,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  modalInfoValue: { fontSize: 12, color: "#FFF", fontWeight: "bold" },
  modalRarityBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    backgroundColor: purple,
  },
  modalRarityText: {
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 1,
    color: "#fff",
  },
});