import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  scroll: { flex: 1 },

  // ── Header ──────────────────────────────────────────────────────────────────
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerSub: {
    fontSize: 10,
    color: colors.textFaint,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  headerTitle: { fontSize: 24, fontWeight: "bold", color: "#fff" },

  // ── Busca ────────────────────────────────────────────────────────────────────
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
    padding: 0,
  },

  // ── Filtros ──────────────────────────────────────────────────────────────────
  filtrosScroll: { marginBottom: 16 },
  filtrosContent: { paddingHorizontal: 16, gap: 8 },
  filtroPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  filtroPillAtivo: {
    backgroundColor: colors.green,
    borderColor: colors.green,
  },
  filtroTexto: { fontSize: 12, color: colors.textMuted, fontWeight: "600" },
  filtroTextoAtivo: { color: "#fff" },

  // ── Resumo Grid ──────────────────────────────────────────────────────────────
  resumoGrid: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 8,
    marginBottom: 24,
  },
  resumoCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    height: 60,
  },
  resumoValor: { fontSize: 16, fontWeight: "bold", color: "#fff" },
  resumoLabel: { fontSize: 9, color: colors.textFaint, marginTop: 2 },

  // ── Cards Favoritos (grid 2 colunas) ─────────────────────────────────────────
  favoritosSection: { paddingHorizontal: 16, marginBottom: 24 },
  favoritosSectionTitle: {
    fontSize: 11,
    color: colors.textFaint,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  favoritosGrid: { flexDirection: "row", gap: 10 },
  favoritoCard: {
    flex: 1,
    backgroundColor: colors.greenDark,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.green,
    minHeight: 130,
    justifyContent: "space-between",
  },
  favoritoCardSemTitulo: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderColor: "rgba(255,255,255,0.08)",
  },
  favoritoTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  favoritoCodigo: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#fff",
    letterSpacing: -0.5,
  },
  favoritoCodigoImage: {
    width: 48,
    height: 32,
    borderRadius: 4,
  },
  favoritoXpBadge: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  favoritoXpText: { fontSize: 10, color: colors.goldLight, fontWeight: "bold" },
  favoritoNome: { fontSize: 15, fontWeight: "bold", color: "#fff", marginBottom: 2 },
  favoritoSub: { fontSize: 11, color: colors.textMuted, marginBottom: 10 },
  favoritoBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  favoritoTitulosRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  favoritoTitulosTexto: { fontSize: 12, color: colors.goldLight, fontWeight: "bold" },
  favoritoColetadaBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Lista principal ──────────────────────────────────────────────────────────
  section: { paddingHorizontal: 16, marginBottom: 20 },
  sectionTitle: {
    fontSize: 11,
    color: colors.textFaint,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 12,
    textTransform: "uppercase",
  },

  // ── Item de País ─────────────────────────────────────────────────────────────
  paisItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    gap: 12,
  },
  paisItemColetado: {
    backgroundColor: "rgba(15, 110, 86, 0.08)",
    borderColor: "rgba(15, 110, 86, 0.25)",
  },
  paisCodigoContainer: {
    width: 46,
    height: 46,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  paisCodigo: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#fff",
    letterSpacing: 0.5,
  },
  paisCodigoImage: {
    width: 42,
    height: 28,
    borderRadius: 4,
  },
  paisInfo: { flex: 1 },
  paisNome: { fontSize: 15, fontWeight: "bold", color: "#fff" },
  paisSubRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 2 },
  paisSub: { fontSize: 12, color: colors.textMuted },
  paisTitulosBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(239, 159, 39, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
  },
  paisTitulosTexto: { fontSize: 10, color: colors.goldLight, fontWeight: "bold" },
  paisRightCol: { alignItems: "flex-end", gap: 6 },
  paisXp: { fontSize: 11, fontWeight: "bold", color: colors.goldLight },
  paisColetadaBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(15, 110, 86, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.green,
  },
  paisNaoColetadaBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },

  // ── Detalhe ──────────────────────────────────────────────────────────────────
  detailHero: {
    height: 200,
    backgroundColor: colors.greenDark,
    justifyContent: "flex-end",
    padding: 20,
  },
  detailHeroOverlay: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  detailBackBtn: {
    position: "absolute",
    top: 20,
    left: 20,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  detailCodigoGrande: {
    fontSize: 64,
    fontWeight: "bold",
    color: "rgba(255,255,255,0.12)",
    position: "absolute",
    right: 20,
    bottom: 16,
    letterSpacing: -2,
  },
  detailCodigoGrandeImage: {
    position: "absolute",
    right: 20,
    bottom: 16,
    width: 100,
    height: 67,
    borderRadius: 6,
    opacity: 0.6,
  },
  detailSub: { fontSize: 10, color: "rgba(255,255,255,0.6)", letterSpacing: 1, textTransform: "uppercase" },
  detailTitle: { fontSize: 30, fontWeight: "bold", color: "#fff", marginTop: 4 },
  detailLocalRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 4 },
  detailContinente: { fontSize: 12, color: "rgba(255,255,255,0.7)", fontWeight: "600" },
  detailGrupo: { fontSize: 12, color: "rgba(255,255,255,0.5)" },

  rewardBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  rewardLabel: { fontSize: 11, color: colors.textFaint, marginBottom: 4 },
  rewardText: { fontSize: 16, fontWeight: "bold", color: colors.goldLight },
  rewardIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },

  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 30,
  },
  infoCard: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  infoLabel: { fontSize: 9, color: colors.textFaint, textTransform: "uppercase", marginBottom: 8, letterSpacing: 0.5 },
  infoValor: { fontSize: 20, fontWeight: "bold", color: "#fff" },
  infoSub: { fontSize: 11, color: colors.textMuted, marginTop: 4 },

  sobreSection: { paddingHorizontal: 20, marginBottom: 30 },
  sobreTitulo: { fontSize: 12, color: colors.green, fontWeight: "bold", letterSpacing: 1, textTransform: "uppercase", marginBottom: 16 },
  sobreTexto: { fontSize: 14, color: colors.textPrimary, lineHeight: 22 },

  historicoSection: { paddingHorizontal: 20, marginBottom: 30 },
  historicoItem: { flexDirection: "row", gap: 16, marginBottom: 24 },
  historicoIconCol: { alignItems: "center" },
  historicoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  historicoLinha: {
    position: "absolute",
    top: 40,
    bottom: -24,
    width: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  historicoContent: { flex: 1, paddingTop: 4 },
  historicoTitulo: { fontSize: 15, fontWeight: "bold", color: "#fff", marginBottom: 4 },
  historicoAno: { fontSize: 12, color: colors.textMuted, marginBottom: 4 },
  historicoDesc: { fontSize: 13, color: colors.textFaint, lineHeight: 18 },
  badgeEmBreve: {
    backgroundColor: "rgba(225, 58, 62, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 6,
  },
  badgeEmBreveTexto: { fontSize: 9, color: "#E13A3E", fontWeight: "bold" },

  figurinhaSection: { paddingHorizontal: 20, marginBottom: 40 },
  figurinhaCard: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  figurinhaIcon: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: colors.greenDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.green,
  },
  figurinhaIconTexto: { fontSize: 20, fontWeight: "bold", color: colors.greenLight },
  figurinhaIconImage: {
    width: 52,
    height: 52,
    borderRadius: 12,
  },
  figurinhaInfo: { flex: 1 },
  figurinhaNome: { fontSize: 15, fontWeight: "bold", color: "#fff" },
  figurinhaSub: { fontSize: 11, color: colors.textFaint, marginTop: 2 },
  figurinhaStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(45, 106, 79, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  figurinhaStatusTexto: { fontSize: 11, fontWeight: "bold", color: "#52B788" },

  // ── Jogadores Destaque ───────────────────────────────────────────────────────
  jogadoresSection: { paddingHorizontal: 20, marginBottom: 30 },
  jogadoresRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  jogadorChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  jogadorNome: { fontSize: 13, color: colors.textPrimary, fontWeight: "600" },

  // ── Modal ────────────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: colors.bgCard,
  },
  modalClose: {
    position: "absolute",
    right: 16,
    top: 16,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCodigoContainer: {
    width: 140,
    height: 140,
    borderRadius: 20,
    backgroundColor: colors.greenDark,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.green,
  },
  modalCodigo: { fontSize: 52, fontWeight: "bold", color: "#fff" },
  modalCodigoImage: {
    width: 140,
    height: 140,
    borderRadius: 20,
  },
  modalName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 4,
    textAlign: "center",
  },
  modalSelection: {
    fontSize: 14,
    color: colors.greenLight,
    fontWeight: "600",
    marginBottom: 16,
  },
  modalInfoRow: { flexDirection: "row", gap: 12, marginBottom: 24 },
  modalInfoBadge: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: "center",
  },
  modalInfoLabel: {
    fontSize: 10,
    color: colors.textMuted,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  modalInfoValue: { fontSize: 12, color: "#FFF", fontWeight: "bold" },
  modalRarityBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    backgroundColor: colors.greenDark,
  },
  modalRarityText: {
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 1,
    color: colors.greenLight,
  },
});